<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Assets\Audio\sfx\" />
    <Folder Include="Assets\Audio\music\" />
    <Folder Include="Assets\Images\epilogue\" />
    <Folder Include="Core\" />
    <Folder Include="Entities\" />
    <Folder Include="Managers\" />
    <Folder Include="Utils\" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Forms\BattleArenaForm.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="Forms\BattleArenaQuestionForm.cs">
      <SubType>Form</SubType>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <Content Include="Assets\**\*.*">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Utils\*.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

</Project>
